en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "All content licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), unless otherwise noted. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/trademark-usage) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](https://www.linuxfoundation.org/privacy) and [Terms of Use](https://www.linuxfoundation.org/terms). [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "TODO Group // Talk openly, develop openly"
  params:
    description: "TODO: talk openly, develop openly. We believe we can better improve our open source programs - and our contributions to the open source movement as a whole - by working together."
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: ""
      help_url: ""
    ### calls to action ###
    main_cta:
      text: "Join"
      link: "/join/"
    footer_cta:
      text: "Join TODO"
      link: "/join/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: "about-us"
      name: "About TODO Group"
      url: "/about/about-us/"
      weight: 1
      post: "The mission of the project and its community"
      parent: "about"
    - identifier: "steering-committee"
      name: "Steering Committee"
      url: "/about/steering-committee/"
      weight: 2
      post: "The people who define TODO's goals and provide stewardship in the community"
      parent: "about"
    - identifier: "members"
      name: "Members"
      url: "/about/members/"
      weight: 3
      post: "The organizations supporting OSPO adoption worldwide"
      parent: "about"
    - identifier: "associates"
      name: "Associates"
      url: "/about/associates/"
      weight: 4
      post: "Projects, communities & foundations supporting TODO and OSPO"
      parent: "about"
    - identifier: "charter"
      name: "Member Charter"
      url: "/about/charter/"
      weight: 6
      post: "Charter of The TODO Group General Members (GM) and Steering Committee (SC)"
      parent: "about"
    - identifier: "code-of-conduct"
      name: "Code of Conduct"
      url: "/about/code-of-conduct/"
      weight: 7
      post: "Values that make TODO  a welcoming and safe community"
      parent: "about"
    - identifier: "faq"
      name: "Q&A"
      url: "/about/faqs/"
      weight: 8
      post: "Frequently Asked Questions"
      parent: "about"
    - identifier: "resources"
      name: "Resources"
      url: "/resources/"
      weight: 2
    - identifier: "glossary"
      name: "Glossary"
      url: "/resources/glossary/"
      weight: 1
      post: "Common terms and definitions of OSPO"
      parent: "resources"
    - identifier: "studies"
      name: "Studies"
      url: "/resources/studies/"
      weight: 2
      post: "Maturity model, surveys, and reports to help your OSPO journey"
      parent: "resources"
    - identifier: "mindmap"
      name: "MindMap"
      url: "/resources/mindmap/"
      weight: 3
      post: "Responsibilities, roles, behavior, and team sizes within OSPOs"
      parent: "resources"
    - identifier: "training"
      name: "Training Modules"
      url: "/resources/training/"
      weight: 4
      post: "Free and open courses covering everything you need to know"
      parent: "resources"
    - identifier: "guides"
      name: "Guides"
      url: "/resources/guides/"
      weight: 5
      post: "Open source program management best practices for organizations"
      parent: "resources"
    - identifier: "case-studies"
      name: "Case Studies"
      url: "/resources/case-studies/"
      weight: 6
      post: "Real case studies showcasing the impact of OSPOs on organizations worldwide"
      parent: "resources"
    - identifier: "artwork"
      name: "Brand Guidebook"
      url: "/resources/guidebook/"
      weight: 7
      post: "TODO Brand Guidebook and visual identity"
      parent: "resources"
    - identifier: "community"
      name: "Community"
      url: "/community/"
      weight: 3
    - identifier: "get-started"
      name: "Get started"
      url: "/community/get-started/"
      weight: 1
      post: "Helpful onboarding resources for the community and members"
      parent: "community"
    - identifier: "communication-channels"
      name: "Communication Channels"
      url: "/community/comms/"
      weight: 2
      post: "Engage with the community via TODO chat, forum, and mailing list"
      parent: "community"
    - identifier: "virtual-meetings"
      name: "Meetings and Calendar"
      url: "/community/meetings/"
      weight: 3
      post: "Join OSPOlogy monthly webinars and working group meetings"
      parent: "community"
    - identifier: "events"
      name: "Events"
      url: "/community/events/"
      weight: 4
      post: "Explore events and roundtable meetings around the world"
      parent: "community"
    - identifier: "ambassadors"
      name: "TODO Ambassadors"
      url: "/community/ambassadors/"
      weight: 5
      post: "Experienced practitioners helping others get started in OSPO and TODO"
      parent: "community"
    - identifier: "osponews"
      name: "OSPONews"
      url: "/community/osponews/"
      weight: 6
      post: "The monthly OSPO newsletter"
      parent: "community"
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 4
ja:
  languageName: 日本語
  contentDir: content/ja
  weight: 2
  params:
    title: "TODO Group // Talk openly, develop openly"
    description: "TODO: talk openly, develop openly (オープンに議論し、オープンに開発する). わたしたちは、協力することで、オープンソース プログラムのみならず、オープンソースのムーブメントへの貢献も、総合的に改善できると考えています。"
    ### accessibility ###
    accessibility:
      skip_text: "コンテンツにスキップ"
      help_text: ""
      help_url: ""
    ### calls to action ###
    main_cta:
      text: "参加"
      link: "/join/"
    footer_cta:
      text: "TODOに参加"
      link: "/join/"
    ### copyright (markdown can be used) ###
    copyright: "All content licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), unless otherwise noted. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/trademark-usage) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](https://www.linuxfoundation.org/privacy) and [Terms of Use](https://www.linuxfoundation.org/terms). [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
    github_edit: "このページをGitHubで編集"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "guides"
      name: "ガイド"
      url: "/guides/"
      weight: 1
    - identifier: "faq"
      name: "よくある質問"
      url: "/faqs/"
      weight: 2
zh-cn:
  languageName: 简体中文
  contentDir: content/zh-CN
  weight: 3
  params:
    title: "TODO Group // Talk openly, develop openly"
    description: "TODO: talk openly, develop openly (开放交流，开放开发。)"
    ### accessibility ###
    accessibility:
      skip_text: "跳至内容"
      help_text: ""
      help_url: ""
    ### calls to action ###
    main_cta:
      text: "加入"
      link: "/join/"
    footer_cta:
      text: "加入TODO"
      link: "/join/"
    ### copyright (markdown can be used) ###
    copyright: "All content licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), unless otherwise noted. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/trademark-usage) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](https://www.linuxfoundation.org/privacy) and [Terms of Use](https://www.linuxfoundation.org/terms). [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
    github_edit: "在GitHub上编辑此页面"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "关于"
      url: "/about/"
      weight: 1
    - identifier: "about-us"
      name: "关于 TODO Group"
      url: "/about/about-us/"
      weight: 1
      post: "项目的使命和社区"
      parent: "about"
    - identifier: "steering-committee"
      name: "指导委员会"
      url: "/about/steering-committee/"
      weight: 2
      post: "确定 TODO Group 的目标并在社区中提供管理与指导的人员"
      parent: "about"
    - identifier: "members"
      name: "普通会员"
      url: "/about/members/"
      weight: 3
      post: "支持在全球范围内采用 OSPO 的组织"
      parent: "about"
    - identifier: "associates"
      name: "合作伙伴"
      url: "/about/associates/"
      weight: 4
      post: "支持 TODO 和 OSPO 的项目、社区和基金会"
      parent: "about"
    - identifier: "resources"
      name: "资源"
      url: "/resources/"
      weight: 2
    - identifier: "glossary"
      name: "术语表"
      url: "/resources/glossary/"
      weight: 1
      post: "OSPO 的常用术语和定义"
      parent: "resources"
    - identifier: "studies"
      name: "研究"
      url: "/resources/studies/"
      weight: 2
      post: "成熟度模型、调查和报告，助您的 OSPO 之旅一臂之力"
      parent: "resources"
    - identifier: "mindmap"
      name: "思维导图"
      url: "/resources/mindmap/"
      weight: 3
      post: "OSPO 内部的责任、角色、行为和团队规模"
      parent: "resources"
    - identifier: "training"
      name: "培训"
      url: "/resources/training/"
      weight: 4
      post: "免费开放的课程，涵盖您需要了解的所有知识"
      parent: "resources"
    - identifier: "guides"
      name: "指南"
      url: "/resources/guides/"
      weight: 5
      post: "组织的开源项目管理最佳实践"
      parent: "resources"
    - identifier: "case-studies"
      name: "案例研究"
      url: "/resources/case-studies/"
      weight: 6
      post: "真实案例研究，展示 OSPO 对全球组织的影响"
      parent: "resources"
    - identifier: "community"
      name: "社区"
      url: "/community/"
      weight: 3
    - identifier: "get-started"
      name: "快速开始"
      url: "/community/get-started/"
      weight: 1
      post: "为社区和成员提供有用的学习资料"
      parent: "community"
    - identifier: "blog"
      name: "博客"
      url: "../blog/"
      weight: 4
