baseURL: https://todogroup.org
enableRobotsTXT: true
contentDir: content/en
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
rssLimit: 1
outputs:
  home: ["HTML", "Atom"]
mediaTypes:
  "application/atom":
    suffixes: [xml]

outputFormats:
  Atom:
    mediaType: application/atom
    baseName: feed
    isPlainText: false

# Internationalization
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

languages:
  en:
    languageName: English
    title: "// TODO: Talk openly, develop openly"
    weight: 1
    description: "TODO: talk openly, develop openly. We believe we can better improve our open source programs - and our contributions to the open source movement as a whole - by working together."
    longTitle: "TODO Group // TODO: Talk openly, develop openly"
    footer:
    - title: Home
      link: /
    - title: About
      link: /about
    - title: ğŸ“š Guides & Resources
      link: /guides
    - title: ğŸ™‹ Community & Network
      link: /community
    - title: ğŸ“ Blog
      link: /blog
    - title: ğŸ’š Members
      link: /members
    - title: ğŸ¤ Associates
      link: /associates
    - title: ğŸ‘‹ Join
      link: /join
    - title: ğŸ’¬ Q&A
      link: /faq
  ja:
    languageName: æ—¥æœ¬èª
    title:"// TODO: Talk openly, develop openly"
    contentDir: content/ja
    weight: 2
    description:ã€ŒTODO: talk openly, develop openly (ã‚ªãƒ¼ãƒ—ãƒ³ã«è­°è«–ã—ã€ã‚ªãƒ¼ãƒ—ãƒ³ã«é–‹ç™ºã™ã‚‹). ã‚ãŸã—ãŸã¡ã¯ã€å”åŠ›ã™ã‚‹ã“ã¨ã§ã€ã‚ªãƒ¼ãƒ—ãƒ³ã‚½ãƒ¼ã‚¹ ãƒ—ãƒ­ã‚°ãƒ©ãƒ ã®ã¿ãªã‚‰ãšã€ã‚ªãƒ¼ãƒ—ãƒ³ã‚½ãƒ¼ã‚¹ã®ãƒ ãƒ¼ãƒ–ãƒ¡ãƒ³ãƒˆã¸ã®è²¢çŒ®ã‚‚ã€ç·åˆçš„ã«æ”¹å–„ã§ãã‚‹ã¨è€ƒãˆã¦ã„ã¾ã™ã€‚ã€
    longTitle:"TODO Group // TODO: Talk openly, develop openly"
    footer:
    - title: ãƒ›ãƒ¼ãƒ 
      link: /
    - title: ã‚¬ã‚¤ãƒ‰
      link: /guides
  zh-CN:
    languageName: æ±‰èª
    title:"// TODO: Talk openly, develop openly"
    contentDir: content/zh-CN
    weight: 2
    description:ã€ŒTODO: talk openly, develop openly (å¼€æ”¾çš„æ¢è®¨ï¼Œå¼€è¯šå¸ƒå…¬ã€‚)ã€
    longTitle:"TODO Group // TODO: Talk openly, develop openly"
    footer:
    - title: ä¼ä¸šå¼€æº
      link: /
    - title: æŒ‡å—
      link: /guides


params:
  googleAnalytics:
    id: UA-54779798-1
  keywords:
  - open source
  - todo
  - talk openly
  - develop openly
  - high quality

  slack:
    channel: todogroup
