baseURL: https://todogroup.org
enableRobotsTXT: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
rssLimit: 1
outputs:
  home: ["HTML", "Atom"]
mediaTypes:
  "application/atom":
    suffix: "xml"

outputFormats:
  Atom:
    mediaType: application/atom
    baseName: feed
    isPlainText: false

# Internationalization
defaultContentLanguage: en
languages:
  en:
    title: "// TODO: Talk openly, develop openly"
    weight: 0
  cn:
    title: INSERT CHINESE TITLE
    weight: 1

# Disable Chinese (for now)
disableLanguages:
- cn


params:
  description: "TODO: talk openly, develop openly. We believe we can better improve our open source programs - and our contributions to the open source movement as a whole - by working together."
  longTitle: "TODO Group // TODO: Talk openly, develop openly"
  googleAnalytics:
    id: UA-54779798-1
  keywords:
  - open source
  - todo
  - talk openly
  - develop openly
  - high quality

  slack:
    channel: todogroup

  footer:
  - title: Home
    link: /
  - title: Blog
    link: /blog
  - title: Guides
    link: /guides
  - title: About
    link: /about
  - title: Community
    link: /community
  - title: Members
    link: /members
  - title: Join
    link: /join
  - title: Q&A
    link: /faq

  guides:
    footerText: |
      These resources were created in partnership with the TODO Group: the professional open source program networking group at The Linux Foundation. A special thank you to Pam Baker for writing assistance and the open source program managers who contributed their time and knowledge to making these comprehensive guides. Participating companies include Autodesk, Comcast, Dropbox, Facebook, Google, Intel, Microsoft, Netflix, Oath (Yahoo + AOL), Red Hat, Salesforce, Samsung and VMware. To learn more, visit: [todogroup.org](http://todogroup.org/).
