[build]
publish = "public"
command = "make netlify-build"

[build.environment]
HUGO_VERSION = "0.48"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"
